{% set version = "0.8-19" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-amap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/amap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/amap/amap_{{ version }}.tar.gz
  sha256: 7349ea684b69eba0fcc48f78b7ac09a838d95d3bc0c6a94b6055605ac0291900

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('amap')"           # [not win]
    - "\"%R%\" -e \"library('amap')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=amap
  license: GPL-2.0-or-later
  summary: Tools for Clustering and Principal Component Analysis (With robust methods, and parallelized functions).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: amap
# Version: 0.8-18
# Date: 2019-12-12
# Title: Another Multidimensional Analysis Package
# Author: Antoine Lucas
# Maintainer: Antoine Lucas <antoinelucas@gmail.com>
# Depends: R (>= 3.6.0)
# Suggests: Biobase
# Description: Tools for Clustering and Principal Component Analysis (With robust methods, and parallelized functions).
# License: GPL
# Packaged: 2019-12-12 18:27:09 UTC; antoine
# Repository: CRAN
# Date/Publication: 2019-12-12 19:00:02 UTC
# NeedsCompilation: yes
