# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxfortran_compilergfortrantarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxfortran_compilertoolchain_forttarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EmxbS1gDK8uS9FKVyL1f7unoB6o+KRzAxzKDwCkHO19pmwDb3LQm8uvTxp9Di1s0BFVWqlFZHKrC+BUC/Ig1erpGuxg8Bix7BUqnVXvlhoU/r75JqcAye//Wqu/HSTcBDuMJScSFUynJA9fsEu0Q3ikVX82rexLuXDOe4x9EyoOtmG8+h5KvPPQdo2Ou0flHDRTz3bGwMxF1LUQMeXAQ6iMsqmb1IyaErwB8SHnVtVHgaHXxrTFGSpAsrQGyh04SQDeFgCOSurxS2YR3mqs3PZX8x2YUImJ8xgUp+u6xCHbTNNQwHsKfWUunfucniPNCDaWfWzzQd2qKVd3m/Dsere8OlIK0lCyezMPOD9UltFY9xUD9ki+sOm0Xow1lffhqRK1R2UbnnaXlSek9GXMh3ujQpYk/Ba7z6LgMjFyTF2r7NUdd8QxFyivN7PX4+KE/eV/1O/sgYlt2emzVsKXb1Lt/RsCoTPd2NllyXC9RGdQgpjX3TSdJaMgeh/m88VbfwRDUKW/oov/jfDAH83UPrnfmmPWeZhH2Ylz6WPZiAzElH0iqFA8BjhpzgxuTIwiHYqu8xgbkOmZ0vgFsuXIEMKraMK+Ouv+xq+VquOEVdN1xoAdOODC0z7O7RAmrTRZLaiY3XzibIz/1rZTT36aQlSDE3wb7ga1lAa9kZboBfOM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
