travis:
  secure:
    BINSTAR_TOKEN: chQYvlmUSx6+yq/MsX6i9/cs0CLKl7D2LgNtNIMDI9fVml5UqfWceybqfKBlXiNvgf0Uou0skBMyh7KCOTnO4lw8CVhVXgQCSxLr1p3d0umEjtLdPD0W9BIl7uQv0INTokNGYho8i0dyE9ueW0IwWQce2hLP0MjmduEJyIAyXCtRKW+F0USl+L93cvKiWqgdFeknMWX574zxjndT1fJ9RTTIF9I4APzyacjAZbnrwitgMdvNJLwL5an2o7fF72Vn7jrjb1bP6CcPujxgAQUlTOwbJfnTW+tAog9YSIA8RcEw1lfODhGfM57B6Lqpit7nJ2pJ0tI2qOly9x1ykqFLjbE396TI0Zx+Kx1ODhr1kFL/h2eU6oqrD+QVruq7IUmMcXhhjIvYB9KRyor2MgTAaLSVLIpNnCrjPjWlRmEDkkWcn2Mgrj74zqdO+tCoXAxpbhClE7pdBzQiGsARuEQAAHYh2R3alvoIwmNlQnmBnfyqdlNbtdbBFzm5XqGHuhug7910r0PYnUye+GR8/kFzPh1yaOUxieMlnkH1mlIzeEPqKXIsxidIBMDUYM8zcrqOhW47ExlFYVejkxBVUUvjcRE3mBYgc9H1/xLOGmR9T7xudc9dk5xMUwAD37tomEQqQy2psrb0qLPSg022P3G6h7CLSB55NWG8ExOh3bJAX0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
