appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EmxbS1gDK8uS9FKVyL1f7unoB6o+KRzAxzKDwCkHO19pmwDb3LQm8uvTxp9Di1s0BFVWqlFZHKrC+BUC/Ig1erpGuxg8Bix7BUqnVXvlhoU/r75JqcAye//Wqu/HSTcBDuMJScSFUynJA9fsEu0Q3ikVX82rexLuXDOe4x9EyoOtmG8+h5KvPPQdo2Ou0flHDRTz3bGwMxF1LUQMeXAQ6iMsqmb1IyaErwB8SHnVtVHgaHXxrTFGSpAsrQGyh04SQDeFgCOSurxS2YR3mqs3PZX8x2YUImJ8xgUp+u6xCHbTNNQwHsKfWUunfucniPNCDaWfWzzQd2qKVd3m/Dsere8OlIK0lCyezMPOD9UltFY9xUD9ki+sOm0Xow1lffhqRK1R2UbnnaXlSek9GXMh3ujQpYk/Ba7z6LgMjFyTF2r7NUdd8QxFyivN7PX4+KE/eV/1O/sgYlt2emzVsKXb1Lt/RsCoTPd2NllyXC9RGdQgpjX3TSdJaMgeh/m88VbfwRDUKW/oov/jfDAH83UPrnfmmPWeZhH2Ylz6WPZiAzElH0iqFA8BjhpzgxuTIwiHYqu8xgbkOmZ0vgFsuXIEMKraMK+Ouv+xq+VquOEVdN1xoAdOODC0z7O7RAmrTRZLaiY3XzibIz/1rZTT36aQlSDE3wb7ga1lAa9kZboBfOM=}
